os: linux
dist: trusty
sudo: required
group: edge
language: c
branches:
  except:
    - /^.*-automated-build$/
    - /^[0-9]+\.[0-9]+\.[0-9]+/
before_install:
  - wget http://ww1.microchip.com/downloads/en/DeviceDoc/avr8-gnu-toolchain-3.5.4.1709-linux.any.x86_64.tar.gz || wget http://qmk.fm/avr8-gnu-toolchain-3.5.4.1709-linux.any.x86_64.tar.gz
install:
  - tar -zxf avr8-gnu-toolchain-3.5.4.1709-linux.any.x86_64.tar.gz
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/avr8-gnu-toolchain-linux_x86_64/bin"
before_script:
  - avr-gcc --version
script:
- make ergodox_ez:bepo_tm_style
after_success:
  ls
addons:
  apt:
    packages:
    - dfu-programmer
    - pandoc
    - gcc-arm-none-eabi
    - binutils-arm-none-eabi
    - libnewlib-arm-none-eabi
    - diffutils
    - dos2unix
  artifacts:
    s3_region: "us-west-2"
    paths:
      - ergodox_ez_bepo_tm_style.hex
    targetPaths: 
      - "artifacts/$TRAVIS_BUILD_NUMBER"